##################################
#      PanickyAdmin plugin       #
#               by               #
#          SpaicyGaming          #
##################################
Messages:
  Prefix: '&8[&bPanickyAdmin&8]'
  noPerms: '&cSorry, you don''t have enought permissions.'
  unknwCmd: '&cUnknown command, use /panickyadmin help.'
  panic: '&c&lPanic mode activated!'
Commands:
  - whitelist on
  #- stop


####DO NOT TOUCH###
ConfigVersion: 1.1
CheckUpdates: true