##################################
#      PanickyAdmin plugin       #
#               by               #
#          SpaicyGaming          #
##################################
Messages:
  Prefix: '&8[&bPanickyAdmin&8]'
  noPerms: '&cSorry, you don''t have enought permissions.'
  unknwCmd: '&cUnknown command, use /panickyadmin help.'
  panic: '&c&lPanic mode activated!'
  unpanic: '&a&lPanic mode disabled'
Commands:
  # player or console
  cmdsExecutor: player
  # {sender} will be replaced by the CommandSender's name
  # (only if the command sender is a player)
  panic:
    - whitelist add {sender}
    - whitelist on
    #- stop
  unpanic:
    - whitelist off
    - whitelist remove {sender}
    # whatever you want

####DO NOT TOUCH###
ConfigVersion: 1.4
CheckUpdates: true