main: io.github.spaicygaming.panickyadmin.PanickyAdmin

name: PanickyAdmin
author: SpaicyGaming
website: https://www.spigotmc.org/resources/panickyadmin.43625/
version: 1.4

commands:
   panickyadmin:
     description: Main command.
   panic:
     description: Executes all panic commands.
   unpanic:
     description: Executes all unpanic commands.